export const msg = {
  "connected": "Połączono!",
  "connected-text": "Pomyślnie połączono z kasynem!",
  "ERROR": "Error",
  "EMAIL_OR_LOGIN_EXISTS" : "Email lub login istnieje",
  "connection" : "Połączono",
  "avalaibleCoinsTitle" : "Dostępne żetony",
  "basketGameBank" : "Pula nagród w grze 'Basket'",
  "onlinePlayers" : "Grający teraz",
  "account" : "Konto",
  "payments" : "Płatności",
  "basket" : "Koszyczek",
  "gunner" : "Rewolwer",
  "home" : "Główna",
  'REFRESHING' : 'Odświeżam...',
  'TOKEN_IS_ACTIVATED' : 'Token jest już aktywowany.',
  'NOT_ACTIVATED' : 'Konto nieaktywne. Sprawdź e-mail!',
  'SUCCESSFUL_ACTIVATION' : 'Aktywacja pomyślna! Możesz się zalogować.',
  'BAD_NICKNAME_OR_TOKEN' : 'Zły login lub hasło.',
  'SUCCESSFULL_LOGIN' : 'Zalogowano!',
  'SUCCESSFULL_REGISTERED' : 'Pomyślna rejestracja, sprawdź e-mail!',
  'UNDEFINED_ERROR' : 'Wystąpił problem... Spróbuj ponownie, albo skontaktuj się z administracją.',
  'SUCCESS' : 'Sukces!',
  'MAIL_WITH_NEXT_STEPS_HAS_BEEN_SENT_TO_YOUR_ADRESS' : 'E-mail został wysłany na Twój adres.',
  'SORRY_THERE_IS_AN_PROBLEM_WITH_THIS_ACTION_TRY_AGAIN_LATER' : 'Wystąpił problem... Spróbuj ponownie.',
  'PASSWORD_HAS_BEEN_CHANGED' : 'Hasło zmienione!',
  "notlogged" : "Niezalogowany",
  "username" : "Nazwa użytkownika",
  "password" : "Hasło",
  "email" : "E-mail",
  "register" : "Zarejestruj",
  "login" : "Zaloguj",
  "clickHereIfYouWantToLogin" : "Kliknij tutaj, jeżeli chcesz się zalogować",
  "clickHereIfYouWantToRegister" : "Kliknij tutaj, jeżeli chcesz się zarejestrować",
  "clickHereIfYouWantToChangePassword" : "Kliknij tutaj, jeżeli chcesz zmienić hasło",
  "newPassword" : "Nowe hasło",
  "sendRequest" : "Wyślij zapytanie",
  "BAD_LOGIN_OR_PASSWORD" : "Zły login lub hasło",
  "passwordChange" : "Zmiana hasła",
  "accountInformations" : "Informacje o koncie",
  "nickname" : "Nazwa użytkownika",
  "activated" : "Aktywowano",
  "balance" : "Saldo",
  "Win" : "Wygrana!",
  "winmuch" : "Ilość wygranej",
  "Lose" : "Przegrana :(",
  "tryagain" : "Spróbuj ponownie!",
  "SORRY YOU DONT HAVE ENOUGH MONEY CHARGE YOURSELF!" : "Przepraszam, nie masz pieniędzy na tą akcję.",
}
