export const msg = {
  "connected": "Connected",
  "connected-text": "Successfully connected to casino, good luck!",
  "ERROR": "Error",
  "EMAIL_OR_LOGIN_EXISTS" : "Email or login exists",
  "connection" : "Connected",
  "avalaibleCoinsTitle" : "Avalaible chips",
  "basketGameBank" : "Sum of bank of the 'Basket' game",
  "onlinePlayers" : "Online players",
  "account" : "Account",
  "payments" : "Payments",
  "basket" : "Basket game",
  "gunner" : "Gunner",
  "home" : "Home",
  'REFRESHING' : 'Refreshing...',
  'TOKEN_IS_ACTIVATED' : 'Token is already activated.',
  'NOT_ACTIVATED' : 'Account not activated. Check e-mail.',
  'SUCCESSFUL_ACTIVATION' : 'Success activation! You can now log-in.',
  'BAD_NICKNAME_OR_TOKEN' : 'Bad nickname or token.',
  'SUCCESSFULL_LOGIN' : 'Successful login.',
  'SUCCESSFULL_REGISTERED' : 'Succsesful register. Check your e-mail!',
  'UNDEFINED_ERROR' : 'There was a problem... Please try again later or contact administrator.',
  'SUCCESS' : 'Success!',
  'MAIL_WITH_NEXT_STEPS_HAS_BEEN_SENT_TO_YOUR_ADRESS' : 'Mail with next steps has been sended to your e-mail.',
  'SORRY_THERE_IS_AN_PROBLEM_WITH_THIS_ACTION_TRY_AGAIN_LATER' : 'There was a problem... Please try again later.',
  'PASSWORD_HAS_BEEN_CHANGED' : 'Password changed!',
  "notlogged" : "Not logged",
  "username" : "Username",
  "password" : "Password",
  "email" : "E-mail",
  "register" : "Register",
  "login" : "Login",
  "clickHereIfYouWantToLogin" : "Click here if you want to login",
  "clickHereIfYouWantToRegister" : "Click here if you want to register",
  "clickHereIfYouWantToChangePassword" : "Click here if you want to change password",
  "newPassword" : "New password",
  "sendRequest" : "Send request",
  "BAD_LOGIN_OR_PASSWORD" : "Bad login or password",
  "passwordChange" : "Password change",
  "accountInformations" : "Account informations",
  "nickname" : "Nickname",
  "activated" : "Activated",
  "balance" : "Balance",
  "Win" : "Win!",
  "winmuch" : "Ammount of win",
  "Lose" : "Lose :(",
  "tryagain" : "Try again!",
  "SORRY YOU DONT HAVE ENOUGH MONEY CHARGE YOURSELF!" : "Sorry, you don't have money for this action.",
}
